//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MissingPersonData
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Address { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string SpouseName { get; set; }
        public string ImagePath { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.DateTime> MissingDate { get; set; }
        public Nullable<bool> Found { get; set; }
        public System.DateTime CreatedDatetime { get; set; }
        public Nullable<System.DateTime> UpdateDatetime { get; set; }
    }
}
